### ISSUE TITLE
[Feature] Quarkus Extension

### ISSUE THREAD

**Issue by rdehuyss** [jobrunr/jobrunr#177]
**Is your feature request related to a problem? Please describe.**
I would like a Quarkus Extension

**Describe the solution you'd like**
I would like a Quarkus Extension

**Describe alternatives you've considered**
Doing the work manually as described on JobRunr.io

### Todo
- [x] Create working Quarkus Extension
- [x] Add support for Recurring annotation
- [x] Recurring annotation unit tests (Blocked - waiting on Quarkus team)
- [x] MicroMeter support
- [x] MicroMeter unit tests
- [x] Test MicroMeter support in a Quarkus App
- [x] HealthIndicator support
- [x] HealthIndicator unit tests
- [x] Test HealthIndicator support in a Quarkus App
- [ ] Test Quarkus App with different StorageProviders  (SQL, MongoDB, ElasticSearch)
- [x] Update Quarkus example
- [x] Update documentation on website
- [ ] Add as a quarkus extension in quarkus universe?
