### ISSUE TITLE
[Feature] Better Spring integration

### ISSUE THREAD

**Issue by rdehuyss** [jobrunr/jobrunr#178]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to use @PostConstruct to schedule my Recurring jobs

**Describe the solution you'd like**
I would like an annotation for my Recurring jobs so that they are automatically discovered.

### Todo
- [x] Recurring annotation
- [x] MicroMeter support
- [x] MicroMeter unit tests
- [x] Test MicroMeter support in a Spring App
- [x] HealthIndicator support
- [x] HealthIndicator unit tests
- [x] Test HealthIndicator support in a Spring App

**Comment by rdehuyss** [comment]
Solved with commit 4feb7f5655d1b36e9330e69ad867f7cb95d0c024
