### ISSUE TITLE
[Feature] Micronaut integration

### ISSUE THREAD

**Issue by rdehuyss** [jobrunr/jobrunr#179]
**Is your feature request related to a problem? Please describe.**
I would like to have JobRunr integrated with Micronaut

### Todo
- [x] Create working Micronaut Integration
- [x] Add support for Recurring annotation
- [x] Recurring annotation unit tests (Blocked)
- [x] MicroMeter support
- [x] MicroMeter unit tests
- [x] Test MicroMeter support in a Micronaut App
- [x] HealthIndicator support
- [x] HealthIndicator unit tests
- [x] Test HealthIndicator support in a Micronaut App
- [x] Test Micronaut App with different StorageProviders
- [x] Create Micronaut App example
- [x] Update documentation on website
